package store

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"market/internal/v2/db"
	"market/internal/v2/types"
)

// PatchImageAnalysisImage replaces image_analysis -> 'images' -> imageName
// across every user_applications row that already references this image,
// and returns the distinct list of user_ids whose rows were touched.
//
// The patch is a single jsonb_set UPDATE with RETURNING user_id so
// "find rows + patch + collect affected users" happens in one network
// round-trip and one transaction, without iterating the table in
// application memory.
//
// Filter semantics:
//   - image_analysis IS NULL is excluded — there is no images map to
//     patch and jsonb_set on NULL would yield NULL (which would also
//     trip the ck_..._image_analysis_object CHECK constraint).
//   - the existence check (jsonb_exists on image_analysis -> 'images')
//     makes the operation strictly idempotent over the "image not
//     present" case; we deliberately do NOT create the key (chart-repo
//     only emits image_info_updated for images it has previously
//     analysed, so a missing key here means the row's images map was
//     generated by an older render that did not include the image —
//     re-render will fix it).
//
// We use the jsonb_exists() function form rather than the `?` operator
// because gorm's parameter binding treats `?` as a placeholder; the
// function form has no such ambiguity. Likewise jsonb_set's path
// argument is built via ARRAY[]::text[] so an imageName containing
// "/" or other registry-name punctuation needs no escaping.
//
// info is marshalled via encoding/json so the resulting JSONB shape
// matches what UpsertRenderSuccess writes via gorm + models.JSONB —
// the two writers therefore produce mutually-compatible payloads.
func PatchImageAnalysisImage(
	ctx context.Context,
	imageName string,
	info *types.ImageInfo,
) (affectedUsers []string, err error) {
	imageName = strings.TrimSpace(imageName)
	if imageName == "" {
		return nil, fmt.Errorf("PatchImageAnalysisImage: empty imageName")
	}
	if info == nil {
		return nil, fmt.Errorf("PatchImageAnalysisImage: nil info")
	}

	infoJSON, mErr := json.Marshal(info)
	if mErr != nil {
		return nil, fmt.Errorf("PatchImageAnalysisImage: marshal info for %s: %w", imageName, mErr)
	}

	gdb := db.Global()
	if gdb == nil {
		return nil, fmt.Errorf("postgres not initialised; db.Open must run before PatchImageAnalysisImage")
	}

	const query = `
UPDATE user_applications
   SET image_analysis = jsonb_set(
           image_analysis,
           ARRAY['images', ?]::text[],
           ?::jsonb,
           false)
 WHERE image_analysis IS NOT NULL
   AND jsonb_exists(image_analysis -> 'images', ?)
RETURNING user_id`

	rows, err := gdb.WithContext(ctx).Raw(query, imageName, string(infoJSON), imageName).Rows()
	if err != nil {
		return nil, fmt.Errorf("patch image analysis for %s: %w", imageName, err)
	}
	defer rows.Close()

	seen := make(map[string]struct{})
	for rows.Next() {
		var uid string
		if err := rows.Scan(&uid); err != nil {
			return nil, fmt.Errorf("scan affected user for %s: %w", imageName, err)
		}
		if uid == "" {
			continue
		}
		if _, ok := seen[uid]; ok {
			continue
		}
		seen[uid] = struct{}{}
		affectedUsers = append(affectedUsers, uid)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate affected users for %s: %w", imageName, err)
	}
	return affectedUsers, nil
}
